version: "3.7"
services:
  nginx:
    image: nginx:latest
    networks:
      - network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - static:/home/SEEYA-ARCHIVE-BACK/staticfiles
      - media:/home/SEEYA-ARCHIVE-BACK/media
    ports:
      - "80:80"

    depends_on:
      - gunicorn_server
    restart: always


  gunicorn_server:
    image: django_server:1
    networks:
      - network
    volumes:
      - static:/home/SEEYA-ARCHIVE-BACK/staticfiles
      - media:/home/SEEYA-ARCHIVE-BACK/media
    restart: always
    secrets:
      - SECRET_KEY
      - MY_AWS_SECRET_ACCESS_KEY
      - MY_AWS_ACCESS_KEY_ID
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - HOST
      - KAKAO_REST_API_KEY
      - KAKAO_REDIRECT_URI
      - KAKAO_SECRET_KEY
      - KAKAO_ADMIN_KEY

networks:
  network:

volumes:
  static:
  media:

secrets:
  SECRET_KEY:
    external: true
  MY_AWS_SECRET_ACCESS_KEY:
    external: true
  MY_AWS_ACCESS_KEY_ID:
    external: true
  KAKAO_REST_API_KEY:
    external: true
  KAKAO_REDIRECT_URI:
    external: true
  KAKAO_SECRET_KEY:
    external: true
  KAKAO_ADMIN_KEY:
    external: true
  DB_NAME:
    external: true
  DB_USER:
    external: true
  DB_PASSWORD:
    external: true
  DB_HOST:
    external: true
  DB_PORT:
    external: true
  HOST:
    external: true