# Generated by Django 4.0.3 on 2022-06-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_nickname',
            new_name='nickname',
        ),
    ]
