# Generated by Django 4.0.3 on 2022-06-29 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seat_reviews', '0008_review_like_users_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='like_users',
            field=models.ManyToManyField(null=True, related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
