# Generated by Django 4.0.3 on 2022-07-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat_reviews', '0010_alter_review_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
