# Generated by Django 4.0.3 on 2022-07-05 01:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seat_reviews', '0011_alter_reviewimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
