# Generated by Django 4.0.3 on 2022-07-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seat_reviews', '0012_review_image_url_array_alter_review_like_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviews',
            new_name='review',
        ),
    ]
